app/src/Entity/Usuario.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsuarioRepository")
 */
class Usuario
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Horario;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Ciudad;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ZIP;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getHorario(): ?string
    {
        return $this->Horario;
    }

    public function setHorario(?string $Horario): self
    {
        $this->Horario = $Horario;

        return $this;
    }

    public function getCiudad(): ?string
    {
        return $this->Ciudad;
    }

    public function setCiudad(string $Ciudad): self
    {
        $this->Ciudad = $Ciudad;

        return $this;
    }

    public function getZIP(): ?int
    {
        return $this->ZIP;
    }

    public function setZIP(?int $ZIP): self
    {
        $this->ZIP = $ZIP;

        return $this;
    }
}

app/src/Form/UsuarioFormType.php
<?php


namespace App\Form;

use App\Entity\Usuario;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsuarioFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('Nombre');
        $builder->add('Email');
        $builder->add('Horario');
        $builder->add('Ciudad', ChoiceType::class, 
            [
                'choices' => [
                    'Madrid' => 'Madrid',
                    'Barcelona' => 'Barcelona',
                    'Valencia' => 'Valencia',
                    'Sevilla' => 'Sevilla'
                ]
            ]
    );
        $builder->add('ZIP');
    }
    
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => Usuario::class
            ]
            );
    }


} 

app/src/Controller/MainController.php
<?php


namespace App\Controller;

use App\Entity\Usuario;
use App\Form\UsuarioFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/", name = "homepage")
     */
    public function index()
    {
        return $this->render(
            'base.html.twig'
        );
    }

    /**
     * @Route("/usuarios", name="listar_usuarios")
     */

    public function listarUsuarios(EntityManagerInterface $em)
    {
        $repositorio = $em->getRepository(Usuario::class);

        $usuarios = $repositorio->findAll();

        return $this->render(
            'Usuarios/list.html.twig',
            [
                'users' => $usuarios
            ]
            );
    }


    /**
     * @Route("/usuarios/nuevo", name="nuevo_usuario")
     */

    public function nuevoUsuario(Request $request, EntityManagerInterface $em)
    {

        $form = $this->createForm(UsuarioFormType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $usuario = $form->getData();

            $em->persist($usuario);
            $em->flush();


            return $this->redirectToRoute('listar_usuarios');
        }

        return $this->render(
            'Usuarios/form.html.twig',
            [
                'formulario' => $form->createView()

            ]
        );
    }

        /**
     * @Route("/usuarios/edit/{id}", name="editar_usuario")
     */

    public function editarUsuario(Usuario $usuario, Request $request, EntityManagerInterface $em)
    {

        $form = $this->createForm(UsuarioFormType::class, $usuario);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $usuario = $form->getData();

            $em->persist($usuario);
            $em->flush();


            return $this->redirectToRoute('listar_usuarios');
        }

        return $this->render(
            'Usuarios/form.html.twig',
            [
                'formulario' => $form->createView()

            ]
        );
    }

}

app/templates/Usuarios/form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="formularioAparte">
    {{ form_start(formulario) }}
     <div class="botonformulario">                                    
        <a href="{{ path('listar_usuarios') }}"><input class="boton" type="submit" value="Añadir"></a>
    {{ form_end(formulario) }}
    </div>
    </div>
{% endblock %}

app/templates/Usuarios/list.html.twig
{% extends 'base.html.twig' %}


{% block body %}

<main class="main-formulario">
    <table>
<table class="table">
  <thead class="table-head">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Email</th>
      <th scope="col">Ciudad</th>
       <th scope="col">ZIP</th>
    </tr>
  </thead>
  <tbody>
    {% for usuario in users %}
    <tr>

      <th scope="row">{{ usuario.id }}</th>
      <td><a href="{{ path('editar_usuario', {id: usuario.id}) }}"> {{ usuario.nombre }} </a></td>
      <td> {{ usuario.email }} </td>
      <td> {{ usuario.ciudad }} </td>
      <td> {{ usuario.zip }} </td>
    </tr>
    {% endfor %}

  </tbody>
</table>



    <button class="boton-nuevo-usuario"> <a href="{{ path('nuevo_usuario') }}">Crear Usuario</a> </button>
</main>

{% endblock %}

app/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}Maleteo{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
            <link href="https://fonts.googleapis.com/css?family=Catamaran&display=swap" rel="stylesheet"> 
            <link rel ="stylesheet" type = "text/css" href = "{{ asset('./Styles/styles.css') }}" />   
        {% endblock %}
    </head>
    <body>
        {% block body %}
            <header>
                <div class="pegatina">
                    <object class="logo" type="image/svg+xml" data="./Images/logo.svg">
                    </object>
                </div>
            </header>
            <main>
                <div class="seccion1">  
                    <div class="row start-md">
                        <div class="col-md-6">
                            <div class="box">
                                <h1 class="gana">Gana dinero guardando equipaje a viajeros como tú</h1>
                                <div class="playstore">
                                    <object class="logo" type="image/svg+xml" data="./Images/app-store.svg"></object>
                                    <object class="logo" type="image/svg+xml" data="./Images/google-play.svg"></object>
                                </div>
                            </div>
                        </div>
                    </div>         
                </div> 
                <div class="seccion2">
                    <div class="titulosegundaseccion">
                        <h1>¿Cómo funciona?</h1>
                    </div>
                    <div class="row around-md">
                            <div class="col-md-4">
                                <div class="botonseccion2">
                                    <p>1</p>
                                </div>
                                <div class="tituloseccion2">
                                    <h2>Date de alta</h2>
                                </div>
                                <div class="parrafoseccion2">
                                    <p>
                                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                                    </p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="botonseccion2">
                                    <p>2</p>
                                </div>
                                <div class="tituloseccion2">
                                    <h2>Publica tus espacios, horarios y tarifas</h2>
                                </div>
                                <div class="parrafoseccion2">
                                    <p>" aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="botonseccion2">
                                    <p>3</p>
                                </div>
                                <div class="tituloseccion2">
                                    <h2>Recibe viajeros y gana dinero</h2>
                                </div>
                                <div class="parrafoseccion2">
                                    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
                                </div>
                            </div>                          
                    </div>
                </div>
                <div class="seccion3">
                    <div class="row start-md">
                        <div class="col-md-6">
                            <img src="./Images/iPhoneX.png"/>
                        </div> 
                        <div class=" col-sm-12 col-md-6">      
                            <div class="formulario col-md-6"> 
                                    <div class="col-md-12">
                                        <div class="tituloformulario">
                                            <h2>Solicita una demo</h2>
                                        </div>
                                    <div class="texto-formulario">
                                    <p> Accede al formulario para que podamos ponernos en contacto contigo</p>
                                    </div>    
                                    </div>
                                    <div class="col-md-12">
                                        <div class="botonformulario">                                    
                                             <a href="{{ path('nuevo_usuario') }}"><input class="boton" type="submit" value="Formulario"></a>
                                        </div>
                                    </div>
                                </form>  
                            </div>                                                                            
                    </div> 
                </div>
                <div class="seccion4">
                    <div class="titulosegundaseccion">
                        <h1>Opiniones de otros guardianes</h1>
                    </div>
                    <div class="tarjetas">
                        <div class="row around-md">
                            <div class="col-md-4">
                                <p class="parrafoinferior">
                                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
                                </p>
                                <h3 class="autor">Carlos Garnacho</h3>
                            </div> 
                            <div class="col-md-4">
                                <p class="parrafoinferior">
                                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
                                </p>
                                <h3 class="autor">Carlos Garnacho</h3>
                            </div> 
                            <div class="col-md-4">
                                <p class="parrafoinferior">
                                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
                                </p>
                                <h3 class="autor">Carlos Garnacho</h3>
                            </div>                                           
                        </div>
                                
                    </div>
                </div> 
                <div class="seccion5">
                        <iframe  class="seccion5" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3037.573844128154!2d-3.6999664213733143!3d40.41829056357178!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd42288400f08e61%3A0x5c83609daf89210a!2sMetro%20Sevilla!5e0!3m2!1ses!2ses!4v1570000967133!5m2!1ses!2ses" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" ></iframe>
                </div>    
            </main>
            <footer>
                    <object class="logo" type="image/svg+xml" data="./Images/logo.svg">
                    </object>
            </footer>  

                {% endblock %}

                {% block javascripts %}
                
                
                {% endblock %}
    </body>
</html>